=== novotnyr/xml-schema-tutorial/samples/110-explicit-namespace/calendar.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:example:calendar"
           elementFormDefault="qualified"
           xmlns:cal="urn:example:calendar"> <!--3-->

    <xs:complexType name="Event">  <!--1-->
        <xs:sequence>
            <xs:element name="date" type="xs:dateTime" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="participants" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="participant" type="xs:string" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="calendar">
        <xs:complexType>
            <xs:sequence>
                <!--2-->
                <xs:element name="event" type="cal:Event"
                            minOccurs="0"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="event" type="cal:Event" />  <!--4-->
</xs:schema>

=== novotnyr/xml-schema-tutorial/samples/110-explicit-namespace/calendar.xml
<cal:calendar xmlns:cal="urn:example:calendar"
              xsi:schemaLocation="urn:example:calendar calendar.xsd"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <cal:event>
        <cal:date>2019-05-30T09:00:00</cal:date>
        <cal:description>Welcome Drink</cal:description>
        <cal:participants> <!--1-->
            <cal:participant>John Doe</cal:participant> <!--2-->
            <cal:participant>Jane Doe</cal:participant> <!--2-->
        </cal:participants>
    </cal:event>
    <cal:event>
        <cal:date>2019-05-30T10:00:00</cal:date>
        <cal:description>Conference</cal:description> <!--3-->
    </cal:event>
</cal:calendar>
